version: '3'
services:
  spark:
    image: openjdk:8-jre-slim
    build:
      context: .
    ports:
      - "4040:4040"  # Example port mapping, you can modify as needed
    volumes:
      - ./spark-data:/spark-data  # Mount a volume for data storage, adjust as needed
    environment:
      SPARK_VERSION: 3.2.4
      HADOOP_VERSION: 3.2
      SPARK_HOME: /spark
    command: ["spark-shell"]
    networks:
      - spark-net

    # Additional functionality
    environment:
      - SPARK_HOME=/spark
    command: ["sh", "-c", "cp ${SPARK_HOME}/conf/spark-defaults.conf.template ${SPARK_HOME}/conf/spark-defaults.conf && sed -i 's/# spark\\.master\\..*/spark\\.master\\..*/' ${SPARK_HOME}/conf/spark-defaults.conf && sed -i 's/# spark\\.serializer\\..*/spark\\.serializer\\..*/' ${SPARK_HOME}/conf/spark-defaults.conf"]
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
